name: CI Pipeline

on:
  push:
    branches:
      - '**'  # This will trigger on pushes to all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if your dependencies are elsewhere

      - name: Run tests
        run: |
          pytest  # Or any custom script to run your tests
          
      - name: Check for errors and fail if tests fail
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed! Blocking push...";
            exit 1;
          fi

